name: CI with Prometheus Metrics

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Push custom metrics to Prometheus PushGateway
        run: |
          # Push a custom metric to the PushGateway (use your own metrics here)
          curl --data "github_actions_build_duration_seconds{status=\"success\"} 42.1" http://localhost:9091/metrics/job/github-actions/instance/${GITHUB_JOB}
          curl --data "github_actions_build_duration_seconds{status=\"failure\"} 56.3" http://localhost:9091/metrics/job/github-actions/instance/${GITHUB_JOB}
